// jasonData.js
let json = `[{"id":1,"first_name":"Leonard","last_name":"Weond","email":"lweond0@seattletimes.com","gender":"Non-binary","salary":4504},
{"id":2,"first_name":"Kimberlee","last_name":"Cervantes","email":"kcervantes1@hao123.com","gender":"Female","salary":7558},
{"id":3,"first_name":"Shadow","last_name":"Maudett","email":"smaudett2@xing.com","gender":"Male","salary":8046},
{"id":4,"first_name":"Katey","last_name":"Baudesson","email":"kbaudesson3@deliciousdays.com","gender":"Agender","salary":4495},
{"id":5,"first_name":"Noll","last_name":"Pflieger","email":"npflieger4@wikipedia.org","gender":"Male","salary":3864},
{"id":6,"first_name":"Mira","last_name":"Boatwright","email":"mboatwright5@ed.gov","gender":"Female","salary":4859},
{"id":7,"first_name":"Lusa","last_name":"McClaughlin","email":"lmcclaughlin6@arizona.edu","gender":"Agender","salary":2816},
{"id":8,"first_name":"Willette","last_name":"Briscam","email":"wbriscam7@independent.co.uk","gender":"Female","salary":6889},
{"id":9,"first_name":"Arther","last_name":"Cranstone","email":"acranstone8@foxnews.com","gender":"Male","salary":3179},
{"id":10,"first_name":"Susette","last_name":"Fryman","email":"sfryman9@wikia.com","gender":"Polygender","salary":7580},
{"id":11,"first_name":"Rourke","last_name":"Tripett","email":"rtripetta@ca.gov","gender":"Male","salary":4152},
{"id":12,"first_name":"Rudolfo","last_name":"Nockolds","email":"rnockoldsb@blogtalkradio.com","gender":"Male","salary":7208},
{"id":13,"first_name":"Durante","last_name":"Duffit","email":"dduffitc@ow.ly","gender":"Male","salary":7582},
{"id":14,"first_name":"Georgine","last_name":"Charke","email":"gcharked@livejournal.com","gender":"Female","salary":5280},
{"id":15,"first_name":"Heinrick","last_name":"Haig","email":"hhaige@sitemeter.com","gender":"Male","salary":3183},
{"id":16,"first_name":"Adolf","last_name":"Desouza","email":"adesouzaf@si.edu","gender":"Male","salary":2713},
{"id":17,"first_name":"Karel","last_name":"Persse","email":"kpersseg@pbs.org","gender":"Male","salary":4795},
{"id":18,"first_name":"Mychal","last_name":"Bartocci","email":"mbartoccih@cmu.edu","gender":"Male","salary":2272},
{"id":19,"first_name":"Jerrilee","last_name":"Chapleo","email":"jchapleoi@ted.com","gender":"Female","salary":2165},
{"id":20,"first_name":"Valery","last_name":"Petrovykh","email":"vpetrovykhj@wordpress.org","gender":"Female","salary":8672}]`;